name: Nix

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.nix"
      - ".github/workflows/nix.yml"
      - flake.lock

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  check:
    name: "Check Flake"
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - name: check
        run: nix flake check --impure
  build:
    name: "Build Package"
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - name: build
        run: nix build .#default --print-out-paths --json